version: 2.1
jobs:
  test:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: make tests
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: make build_docker
