version: 2.1
jobs:
  test:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: make tests
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: make build_docker
  push:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: make push_docker
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - push:
          requires:
            - build
